import "../globals.css";
export const metadata = {
  title: 'My Site',
  description: 'Generated by Next',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
         {children}
        
        </body>
    </html>
  )
}
